### ISSUE TITLE
Ability to turn off the animation when changing the panktis when next line enabled

### ISSUE THREAD

**Issue by sukhpalsingh** [KhalisFoundation/sttm-desktop#497]
Currently, when the user enable next line feature, it is showing an animation which delays the text to appear on the screen.

It will be good if this animation can be turned off from settings to improve the readability when the pankti are changed quickly where the kirtan is done in fast pace to quickly switch panktis. Current animation is causing a readibility issue in these cases.

**Comment by sukhpalsingh** [comment]
the following code do the animation in **_display-next-line.scss** file
```css
.gurbani,
    .translation,
    .teeka,
    .transliteration {
      animation: ease-out 1s, blank 0.2s, backlight 1s 0.2s cubic-bezier(0.645, 0.05, 0.355, 1);
    }
```
